apiVersion: v1
kind: Service
metadata:
  name: student-management
  namespace: devops
  labels:
    app: student-management
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
    nodePort: 30080

