apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops
type: Opaque
stringData:
  # Credentials MySQL (sécurisé)
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpassword"

