apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops
data:
  # URL de la base de donn√©es (non sensible)
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_PROFILES_ACTIVE: "docker"

