apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-database: studentdb
  mysql-user: studentuser
  mysql-password: studentpass

